"""Added MedicalTestResult model.

Revision ID: 4cc35a6d8bd3
Revises: 662b46e8e951
Create Date: 2023-03-15 09:06:14.956208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc35a6d8bd3'
down_revision = '662b46e8e951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('date_tested', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_test_result')
    # ### end Alembic commands ###
